 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: caption_coco_opt2.7b_gram
  load_finetuned: False

  pretrained: "/ibex/ai/home/kimds/Research/P2/withLLM/implementation/LAVIS/lavis/output/BLIP2/Pretrain_stage2/20230727134/checkpoint_9.pth"
  finetuned:

  # vit encoder
  vit_model: "gram"
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # OPT
  opt_model: "facebook/opt-2.7b"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip_image_train_gram"
          image_size: 224
        eval:
          name: "blip_image_eval_gram"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
